### PR TITLE
Collision with obtacles

### PR DESCRIPTION
**Pull request by Malinsund**
push it in to main =)

### CODE REVIEW

**Comment by CatAvadani** [comment]
Great job!

**Review by CatAvadani — COMMENTED** [review]
The code is working as expected.

**Comment by CatAvadani** [comment]
Great job!

**Review by CatAvadani — COMMENTED** [review]
The code is working as expected.

**Review by Maryamakeyf — APPROVED** [review]

**Review by CatAvadani — APPROVED** [review]

**Pull request merged**
